object Versions {
    const val androidCompileSdk = 33
    const val androidMinSdk = 25
    const val androidTargetSdk = 33

    const val androidGradlePlugin = "7.4.2"
    const val androidxActivity = "1.5.1"
    const val androidxAppCompat = "1.5.0"
    const val androidxConstraintLayout = "2.1.4"
    const val androidxCore = "1.8.0"
    const val androidxJUnit = "1.1.3"
    const val androidxLifecycle = "2.5.1"
    const val androidxNavigation = "2.5.1"
    const val androidxSplashScreen = "1.0.0"
    const val composeCompiler = "1.3.2"
    const val compose = "1.3.0"
    const val composeMaterialIcons = "1.3.0-beta01"
    const val crashlyticsClasspath = "2.9.1"
    const val espresso = "3.4.0"
    const val exoplayer = "2.18.1"
    const val firebase = "30.3.2"
    const val googleServices = "4.3.13"
    const val gradleVersionsPlugin = "0.42.0"
    const val jUnit = "4.13.2"
    const val kotlin = "1.7.20"
    const val kotlinxSerialization = "1.3.3"
    const val kotlinCoroutines = "1.6.4"
    const val ktor = "2.1.3"
    const val logback = "1.2.23"
    const val material = "1.6.1"
    const val shot = "5.14.1"
    const val showkase = "1.0.0-beta12"
    const val sqlDelight = "1.5.4"
    const val kermit = "1.0.0"
}